source 'https://rubygems.org'

gem 'bcrypt', '3.1.13'
gem 'ruby2_keywords', '0.0.1'
gem 'sinatra', '2.0.8.1'
gem 'sinatra-flash', '0.3.0', require: 'sinatra/flash'

gem 'shotgun', '0.9.2'
gem 'warden', '1.2.6'

gem 'dm-core', '1.2.1'
gem 'dm-migrations', '1.2.0'
gem 'dm-serializer', '1.2.2'
gem 'dm-sqlite-adapter', '1.2.0'
gem 'dm-timestamps', '1.2.0'
gem 'dm-transactions', '1.2.0'
gem 'dm-types', '1.2.2'
gem 'dm-validations', '1.2.0'